import Head from "next/head";
import Header from "@/components/Header";
import styles from "../styles/style.module.scss";
import Timeline from "@/components/Timeline";
import Post from "@/components/Post";
import { useEffect, useState } from "react";
import apiClient from "@/lib/apiClient";
import { useRouter } from "next/navigation"; // 追加

export type User = {
  id: number;
  username: string;
  email: string;
  password: string;
};

export type Post = {
  id: number;
  content: string;
  createdAt: string;
  authorId: number;
  author: User;
};

export default function Home() {
  // useStateを貼り付けてください🤗
  const [posts, setPosts] = useState<Post[]>([]);
  const router = useRouter(); //  ルーターを取得

  // useEffectの処理=画面が表示された直後に１度実行されます🤗
  useEffect(() => {
    // ここに追加する！
    const token = localStorage.getItem("token");
    if (!token) {
      router.push("/login"); // トークンがなければログインページへ
      return;
    }
    // ここに追加する！

    const fetchPosts = async () => {
      try {
        const response = await apiClient.get("/api/posts");
        console.log(response, "response"); //取得できているかチェックしてみましょう🤗
        setPosts(response.data);
      } catch (error) {
        console.error("投稿の取得に失敗しました:", error);
      }
    };

    fetchPosts();
  }, [router]);

  // 追加
  console.log(posts, "データ");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        {/*  */}
        {/* 先ほど作成したHeaderのパーツを呼び出す記述を書きます🤗 */}
        <Header />

        <Timeline setPosts={setPosts} />

        {/* 後で消しますが先に表示の確認をしましょう🤗 */}
        {/* <Button textColor="pink" bg="blue" /> */}

        {/* 表示する時のテクニック🤗 */}
        {posts.map((item, index) => (
          <Post
            key={index}
            content={item.content}
            createdAt={item.createdAt}
            author={item.author}
          />
        ))}
        {/*  */}
      </main>
    </>
  );
}
