import Head from "next/head";
import Header from "@/components/Header";
import styles from "../styles/style.module.scss";
import Timeline from "@/components/Timeline";
import Post from "@/components/Post";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        {/*  */}
        {/* 先ほど作成したHeaderのパーツを呼び出す記述を書きます🤗 */}
        <Header />

        <Timeline />

        <Post />
        {/*  */}
      </main>
    </>
  );
}
